/* --
    Taller Sql : ventas
    Descripción : Script para el taller
    Autor : Juan Felipe Rodriguez Galindo && Nicolas Mendigaño
--*/

--1) Clientes que compraron el producto 86631
-- Proyectar RUT,NOMBRE,APELLIDO,N_PRODUCTO,CANTIDAD VENDIDA

SELECT C.N_NOM_CLIENTE, C.N_APE_CLIENTE, P.N_PRODUCTO, V.K_RUT, VP.V_CANTIDAD
FROM CLIENTE C, PRODUCTO P, VENTA V, VENTA_PRODUCTO VP
WHERE VP.K_producto = 86631 AND
VP.K_PRODUCTO = P.K_PRODUCTO AND
V.K_RUT = C.K_RUT

--2) VENTAS que se compraron en la fecha 4/11/19
-- Proyectar RUT,NOMBRE_PROVEEDOR,N_PRODUCTO,F_VENTA

SELECT PRO.K_RUT, P.N_PRODUCTO, C.N_NOM_CLIENTE, V.F_VENTA
FROM PRODUCTO P, VENTA V, VENTA_PRODUCTO VP, PROVEEDOR PRO
WHERE VP.K_PRODUCTO = P.K_PRODUCTO AND
P.K_RUT = PRO.K_RUT AND
VP.K_PRODUCTO = P.K_PRODUCTO AND
V.F_VENTA = '4/11/2013';

--3) Categorias asociadas a los productos de la factura 861084
-- Proyectar ID y mobre del PRODUCTO, ID y nombre de la CATEGORIA

SELECT K_PRODUCTO, N_PRODUCTO,K_CATEGORIA,N_CATEGORIA
FROM CATEGORIA C, VENTA V, VENTA_PRODUCTO VP, PRODUCTO P
WHERE C.K_CATEGORIA = P.K_CATEGORIA AND V.K_VENTA = VP.K_VENTA AND VP.K_PRODUCTO=P.K_PRODUCTO AND V.K_VENTA = 861064
ORDER BY N_PRODUCTO DESC, N_CATEGORIA DESC;

--4) proveedores de los productos que se vendueron durante el año 2015,
-- ordene por rut  

SELECT PRO.N_RUT, N_CALLE, O_NUMERO, N_BARRIO, N_CIUDAD, F_VENTA
FROM PRODUCTO P, VENTA V, VENTA_PRODUCTO VP, PROVEEDOR PRO
WHERE PRO.K_RUT = P.K_RUT AND V.K_VENTA = VP.K_VENTA AND VP.K_PRODUCTO = P.K_PRODUCTO AND V.F_VENTA BETWEEN '01/01/2015' AND '31/12/2015'
ORDER BY PRO.K_RUT DESC;

--5) Facturas asociadas a pedro sandoval
--

SELECT  C.K_RUT,K_PRODUCTO, N_PRODUCTO, V.K_VENTA
FROM PRODUCTO P, VENTA V, CLIENTE C
WHERE C.N_NOM_CLIENTE = 'Pedro' AND C.N_APE_CLIENTE='Sandoval'

--6) Numero, suma, promedio, maximo y minimo del monto final de ventas expedidas
-- en el año 2010

--TO_CHAR(V_PRECIO,'$999,999.99')
SELECT SUM(v_monto_final) AS "Suma", 
	AVG(v_monto_final) AS "Promedio",
	MAX(v_monto_final) AS "Maximo",
	MIN(v_monto_final) AS "Minimo",
	F_VENTA
FROM VENTA V
WHERE V.F_VENTA BETWEEN '01/01/2010' AND '31/12/2010'
AND AND AND

--7) VENTAS all data que se compraron en la fecha 4/11/19
-- Proyectar RUT,NOMBRE_PROVEEDOR,N_PRODUCTO,F_VENTA

INSERT INTO CATEGORIA values (6412,'TIPICAS', 'Empanadas Tipicas de Colombia traidas desde el ecuador, con sazon venezolana')

--8) 

INSERT ALL
INTO PRODUCTO VALUES (32451,1200*1.9,EMPANADAS,100,981265142137,6412)
INTO PROVEEDOR VALUES (981265142137,'CALLE ',12,'TIBABUYAES','BOGOTA', 'WWW.EMPANADAS.COM') ;

SELECT * FROM PRODUCTO WHERE K_RUT=32451;
SELECT * FROM PROVEEDOR WHERE K_RUT = 981265142137;

--9-10) VENTAS all data que se compraron en la fecha 4/11/19
-- Proyectar RUT,NOMBRE_PROVEEDOR,N_PRODUCTO,F_VENTA
INTO venta(123456, CONVERT(VARCHAR(10), GETDATE(), 103) , 0, 1200*10, 1200, C.K_RUT WHERE C.N_NOM_CLIENTE='David' AND C.N_APE_CLIENTE='Torres')
INSERT INTO venta_producto(32451,123456,10,1200)
